skipsdist = true

envlist = ["unused-code", "unittests"]

[env.unused-code]
deps = ["python-utility-scripts"]
commands = [
  [
    "pyutils-unusedcode",
    "--exclude-function-prefixes",
    "'main','lifespan'",
  ],
]

[env.unittests]
deps = ["uv"]
commands = [
  [
    "uv",
    "run",
    "--group",
    "tests",
    "pytest",
    "server/tests/",
    "--cov=server",
    "--cov-report=html",
    "--cov-report=term-missing",
    "-n",
    "auto",
  ],
]
