skipsdist = true

envlist = ["unused-code", "unittests"]

[env.unused-code]
deps = ["python-utility-scripts"]
commands = [
  [
    "pyutils-unusedcode",
    "--exclude-function-prefixes",
    "'main','lifespan'",
  ],
]

[env.unittests]
deps = ["uv"]
commands = [
  # Single run: pytest-cov uses coverage settings from pyproject; generate term + html reports once
  [
    "uv",
    "run",
    "--group",
    "tests",
    "pytest",
    "server/tests/",
    "-n",
    "auto",
    "--cov",
    "--cov-report=term-missing",
    "--cov-report=html",
  ],
]
